server:
  port: 8090

spring:
  # 全局时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.pzhu.house.model.entity
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

# 日志配置
logging:
  level:
    root: info
    com.pzhu.house.mapper: debug

# Swagger3
springfox:
  documentation:
    swagger-ui:
      enabled: true

# minio
minio:
  endpoint: 'http://127.0.0.1:9000'
  bucket-name: 'house'
  access-key: 'minioadmin'
  secret-key: 'minioadmin'
